/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Pantallas2;

import Pantallas2.MenuPrincipal;
import dto.CarritoDTO;
import dto.CompraDTO;
import dto.MaderaDTO;
import dto.UsuarioDTO;
import interfaz.ICarritoSS;
import interfaz.ICompraSS;
import interfaz.IComprarCarritoSS;
import interfaz.ISalidaSS;
import interfaz.IUsuarioSS;
import java.util.Calendar;
import java.util.List;
import javax.swing.JOptionPane;
import org.bson.types.ObjectId;

/**
 *
 * @author Oley
 */
public class ConfirmarTarjeta2 extends javax.swing.JFrame {

    private IUsuarioSS iUsuarioSS;
    private ICompraSS iCompraSS;
    private String usuarioId;
    private MenuPrincipal menuPrincipal;
    private ICarritoSS iCarritoSS;
    private  String numeroTarjeta;
    private TarjetasDisponibles2 tarjetasDisponibles2;
    private ISalidaSS  iSalidaSS;

    /**
     * Creates new form ConfirmarTarjeta2
     */
    public ConfirmarTarjeta2(IUsuarioSS iUsuarioSS, ICompraSS iCompraSS, String usuarioId, MenuPrincipal menuPrincipal,ICarritoSS iCarritoSS,String numeroTarjeta,TarjetasDisponibles2 tarjetasDisponibles2,ISalidaSS  iSalidaSS) {
        this.iUsuarioSS = iUsuarioSS;
        this.iCompraSS = iCompraSS;
        this.usuarioId = usuarioId;
        this.menuPrincipal = menuPrincipal;
        this.iCarritoSS=iCarritoSS;
        this.numeroTarjeta=numeroTarjeta;
        this.tarjetasDisponibles2=tarjetasDisponibles2;
        this.iSalidaSS=iSalidaSS;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.setBackground(new java.awt.Color(255, 255, 255));
        jTextField1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 282, 290, 70));

        jButton1.setBackground(new java.awt.Color(51, 153, 0));
        jButton1.setText("Continuar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 400, 190, 70));

        jButton2.setBackground(new java.awt.Color(255, 0, 0));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/flecha-izquierda.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 110, 70));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cvvConfirmar.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 610));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     String CVV = jTextField1.getText();
    
    if (!iUsuarioSS.iniciarSesionPorCVV(numeroTarjeta,CVV)) {
        JOptionPane.showMessageDialog(this, "CVV incorrecto", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }
    
    try {
        // 1. Procesar la compra y obtener los IDs de todas las compras
        List<String> compraIds = iCompraSS.comprarCarrito(usuarioId);
        
        // 2. Mostrar ventana de éxito
        this.setVisible(false);
        CompraExitosa2 compraExitosa = new CompraExitosa2(menuPrincipal);
        compraExitosa.setVisible(true);
        
        // 3. Crear una salida para cada compra
        String tipoMovimiento = "Venta";
        for (String compraId : compraIds) {
            iSalidaSS.crearSalidaDesdeCompra(compraId, tipoMovimiento);
        }
        
        // 4. Vaciar el carrito
        iCarritoSS.vaciarCarrito(usuarioId);
        
    } catch (Exception e) {
        System.err.println("Error en el proceso de compra: " + e.getMessage());
        e.printStackTrace();
    }

  
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

this.setVisible(false);
tarjetasDisponibles2.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
