/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Pantallas2;

import Pantallas2.ProductosVenta;
import Pantallas2.MenuPrincipal;
import dto.MaderaDTO;
import interfaz.ICarritoSS;
import interfaz.ICompraSS;
import interfaz.IMaderaSS;
import interfaz.ISalidaSS;
import interfaz.IUsuarioSS;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Oley
 */
public class DetallesProducto extends javax.swing.JFrame {

    private ProductosVenta productosVenta;
    private String nombreProducto;
    private Double precioProducto;
    private String descripcionProducto;
    private int cantidad;
    private String usuarioId;
    private MenuPrincipal menuPrincipal1;
    private String idMadera;
    private IMaderaSS iMaderaSS;
    private ICarritoSS iCarritoSS;
    private ICompraSS iCompraSS;
    private IUsuarioSS iUsuarioSS;
private ISalidaSS  iSalidaSS;
    /**
     * Creates new form DetallesProducto
     */
    public DetallesProducto(ProductosVenta productosVenta, String nombreProducto, Double precioProducto, String descripcionProducto,
             int cantidad, String usuarioId, MenuPrincipal menuPrincipal1, String idMadera, IMaderaSS iMaderaSS, ICarritoSS iCarritoSS,
             ICompraSS iCompraSS, IUsuarioSS iUsuarioSS,ISalidaSS  iSalidaSS
    ) {
        this.productosVenta = productosVenta;
        this.nombreProducto = nombreProducto;
        this.precioProducto = precioProducto;
        this.descripcionProducto = descripcionProducto;
        this.cantidad = cantidad;
        this.usuarioId = usuarioId;
        this.menuPrincipal1 = menuPrincipal1;
        this.idMadera = idMadera;
        this.iMaderaSS = iMaderaSS;
        this.iCarritoSS = iCarritoSS;
        this.iCompraSS = iCompraSS;
        this.iUsuarioSS = iUsuarioSS;
        this.iSalidaSS=iSalidaSS;
        initComponents();
        mostrarDetallesProducto();

    }

    private void mostrarDetallesProducto() {

        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0); // Limpiar tabla

        // Agregar los detalles a la tabla
        model.addRow(new Object[]{"Nombre", nombreProducto});
        model.addRow(new Object[]{"Precio", precioProducto});
        model.addRow(new Object[]{"Descripción", descripcionProducto});
        model.addRow(new Object[]{"cantidad", cantidad});
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setBackground(new java.awt.Color(204, 255, 102));
        jTable1.setForeground(new java.awt.Color(153, 153, 153));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "", " "
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 346, 200));

        jButton3.setBackground(new java.awt.Color(51, 204, 0));
        jButton3.setForeground(new java.awt.Color(0, 0, 0));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/carrito-de-compras.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 480, 140, 80));

        jButton4.setBackground(new java.awt.Color(51, 204, 0));
        jButton4.setForeground(new java.awt.Color(0, 0, 0));
        jButton4.setText("Comprar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 500, 168, 42));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59", "60", "61", "62", "63", "64", "65", "66", "67", "68", "69", "70", "71", "72", "73", "74", "75", "76", "77", "78", "79", "80", "81", "82", "83", "84", "85", "86", "87", "88", "89", "90", "91", "92", "93", "94", "95", "96", "97", "98", "99", "100" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 412, 80, 40));

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("0");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 410, 100, 40));

        jButton2.setBackground(new java.awt.Color(255, 51, 51));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/flecha-izquierda.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Confirmar Compra.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 570));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.setVisible(false);
        productosVenta.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
     if (jComboBox1.getSelectedIndex() != -1) {
        String cantidadStr = (String) jComboBox1.getSelectedItem();
        this.cantidad = Integer.parseInt(cantidadStr); 

        if (this.cantidad == 0) {
            JOptionPane.showMessageDialog(this, "No puedes seleccionar una cantidad de 0.", "Error", JOptionPane.ERROR_MESSAGE);

            jButton3.setEnabled(false);  
            jButton4.setEnabled(false);  
        } else {
            MaderaDTO madera = iMaderaSS.buscarMaderaPorId(idMadera);  

            if (this.cantidad <= madera.getCantidad()) {
                double precioProducto = this.precioProducto;
                double total = cantidad * precioProducto;

                jLabel4.setText(String.format("%.2f", total)); 
                jLabel4.setFont(new java.awt.Font("Tahoma", java.awt.Font.BOLD, 24)); 

                jButton3.setEnabled(true);  
                jButton4.setEnabled(true);  
            } else {
                JOptionPane.showMessageDialog(this, "No hay suficiente cantidad disponible.", "Error", JOptionPane.ERROR_MESSAGE);

                jButton3.setEnabled(false);  
                jButton4.setEnabled(false);  
            }
        }
    }

        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        this.setVisible(false);
        MenuDeTarjetas menuDeTarjetas = new MenuDeTarjetas(this, usuarioId, menuPrincipal1, cantidad, idMadera, iCompraSS, iUsuarioSS,iSalidaSS);
        menuDeTarjetas.setVisible(true);

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        iCarritoSS.agregarProducto(usuarioId, idMadera, cantidad);
        this.setVisible(false);
        MenuCarrito menuCarrito = new MenuCarrito(productosVenta, usuarioId, menuPrincipal1, iMaderaSS, iCarritoSS, iCompraSS, iUsuarioSS,idMadera,iSalidaSS);
        menuCarrito.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
