/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Pantallas2;

import Pantallas2.IniciarSesion;
import dto.UsuarioDTO;
import interfacesDTO.IUsuarioNegocio;
import interfaz.IUsuarioSS;
import javax.swing.JOptionPane;

/**
 *
 * @author Oley
 */
public class RegistrarUsuario extends javax.swing.JFrame {

    private IniciarSesion iniciarSesion;
    private IUsuarioSS iUsuarioSS;

    /**
     * Creates new form RegistrarUsuario
     */
    public RegistrarUsuario(IniciarSesion iniciarSesion, IUsuarioSS iUsuarioSS) {
        this.iniciarSesion = iniciarSesion;
        this.iUsuarioSS = iUsuarioSS;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 250, 40));

        jTextField2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, 250, 40));

        jTextField3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, 250, 40));

        jTextField4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 290, 250, 40));

        jTextField5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 350, 250, 40));

        jTextField6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 410, 250, 40));

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setText("Regresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 490, 140, 50));

        jButton2.setBackground(new java.awt.Color(0, 153, 0));
        jButton2.setText("Registrar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 490, 140, 50));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/RegistroUsuario.png"))); // NOI18N
        jLabel9.setText("jLabel9");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 570));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        this.setVisible(false);
        iniciarSesion.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
//        String nombre = jTextField1.getText();
//        String apellidoPaterno = jTextField2.getText();
//        String apellidoMaterno = jTextField3.getText();
//        String numero = jTextField4.getText();
//        String correo = jTextField5.getText();
//        String contraseña = jTextField6.getText();
//
//        if (nombre.isEmpty() || apellidoPaterno.isEmpty() || apellidoMaterno.isEmpty()
//                || numero.isEmpty() || correo.isEmpty() || contraseña.isEmpty()) {
//
//            JOptionPane.showMessageDialog(this, "Por favor, complete todos los campos.", "Campos vacíos", JOptionPane.WARNING_MESSAGE);
//            return;
//        }
//
//        UsuarioDTO usuarioDTO = new UsuarioDTO();
//        usuarioDTO.setNombre(nombre);
//        usuarioDTO.setApellidoPaterno(apellidoPaterno);
//        usuarioDTO.setApellidoMaterno(apellidoMaterno);
//        usuarioDTO.setNumero(numero);
//        usuarioDTO.setCorreo(correo);
//        usuarioDTO.setContraseña(contraseña);
//
//        iUsuarioSS.agregarUsuario(usuarioDTO);
//        this.setVisible(false);
//        iniciarSesion.setVisible(true);

  
 String nombre = jTextField1.getText();
    String apellidoPaterno = jTextField2.getText();
    String apellidoMaterno = jTextField3.getText();
    String numero = jTextField4.getText();
    String correo = jTextField5.getText();
    String contraseña = jTextField6.getText();

    if (nombre.isEmpty() || apellidoPaterno.isEmpty() || apellidoMaterno.isEmpty()
            || numero.isEmpty() || correo.isEmpty() || contraseña.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Por favor, complete todos los campos.", "Campos vacíos", JOptionPane.WARNING_MESSAGE);
        return;
    }

    // Validar que el nombre y apellidos solo contengan letras
    if (!nombre.matches("[a-zA-Z]+")) {
        JOptionPane.showMessageDialog(this, "El nombre debe contener solo letras.", "Error en el nombre", JOptionPane.ERROR_MESSAGE);
        return;
    }
    if (!apellidoPaterno.matches("[a-zA-Z]+")) {
        JOptionPane.showMessageDialog(this, "El apellido paterno debe contener solo letras.", "Error en el apellido paterno", JOptionPane.ERROR_MESSAGE);
        return;
    }
    if (!apellidoMaterno.matches("[a-zA-Z]+")) {
        JOptionPane.showMessageDialog(this, "El apellido materno debe contener solo letras.", "Error en el apellido materno", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Validar que el numero solo contenga números
    if (!numero.matches("[0-9]+")) {
        JOptionPane.showMessageDialog(this, "El número debe contener solo dígitos.", "Error en el número", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Validar que el correo contenga un dominio válido
    if (!(correo.endsWith("@gmail.com") || correo.endsWith("@hotmail.com"))) {
        JOptionPane.showMessageDialog(this, "El correo debe ser de dominio @gmail.com o @hotmail.com.", "Error en el correo", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Validar que la contraseña contenga al menos una mayúscula y un número
    if (!contraseña.matches(".*[A-Z].*") || !contraseña.matches(".*[0-9].*")) {
        JOptionPane.showMessageDialog(this, "La contraseña debe contener al menos una mayúscula y un número.", "Error en la contraseña", JOptionPane.ERROR_MESSAGE);
        return;
    }

    UsuarioDTO usuarioDTO = new UsuarioDTO();
    usuarioDTO.setNombre(nombre);
    usuarioDTO.setApellidoPaterno(apellidoPaterno);
    usuarioDTO.setApellidoMaterno(apellidoMaterno);
    usuarioDTO.setNumero(numero);
    usuarioDTO.setCorreo(correo);
    usuarioDTO.setContraseña(contraseña);

    iUsuarioSS.agregarUsuario(usuarioDTO);
    this.setVisible(false);
    iniciarSesion.setVisible(true);














// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
